@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Fri Jan 31 02:20:15 -0500 2025
REM SW Build 5164865 on Thu Sep  5 14:37:11 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L axi_vip_v1_1_18 -L processing_system7_vip_v1_0_20 -L axi_vip_v1_1_17 -L processing_system7_vip_v1_0_19 -L xilinx_vip -prj design_1_wrapper_vlog.prj"
call xvlog  --incr --relax -L uvm -L axi_vip_v1_1_18 -L processing_system7_vip_v1_0_20 -L axi_vip_v1_1_17 -L processing_system7_vip_v1_0_19 -L xilinx_vip -prj design_1_wrapper_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
REM compile VHDL design sources
echo "xvhdl --incr --relax -prj design_1_wrapper_vhdl.prj"
call xvhdl  --incr --relax -prj design_1_wrapper_vhdl.prj -log xvhdl.log
call type xvhdl.log >> compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
